version: "2"
services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    volumes:
      - .target/kafka-connect-colormeshop-1.0-SNAPSHOT-package/share/java:/connectors
